FROM wbk--mern-playground__core:latest as builder
COPY ./frontend/apps/frequently-asked-questions-app ./frontend/apps/frequently-asked-questions-app
RUN yarn install
CMD [ "yarn", "develop:frequently-asked-questions-app"]