import type { Recipe, Challenge, SpoutType } from '@/types';

export const SPOUT_TYPES: SpoutType[] = [
  { id: 'standard', name: 'Standard Speed Pour', flow_rate_multiplier: 1.0, description: 'Most common bar spout' },
  { id: 'screened', name: 'Screened Speed Pour', flow_rate_multiplier: 0.95, description: 'With built-in strainer' },
  { id: 'measured', name: 'Measured Pour', flow_rate_multiplier: 0.8, description: 'Controlled flow rate' },
  { id: 'free-flow', name: 'Free Flow', flow_rate_multiplier: 1.15, description: 'Maximum flow speed' },
  { id: 'olive-oil', name: 'Olive Oil Style', flow_rate_multiplier: 0.7, description: 'Slower, controlled pour' },
  { id: 'tapered', name: 'Tapered Spout', flow_rate_multiplier: 1.05, description: 'Slightly faster flow' },
  { id: 'dust-cap', name: 'Dust Cap Speed', flow_rate_multiplier: 0.98, description: 'With protective cap' },
  { id: 'flip-top', name: 'Flip Top', flow_rate_multiplier: 0.9, description: 'Hinged cap design' },
  { id: 'chrome', name: 'Chrome Speed', flow_rate_multiplier: 1.02, description: 'Metal construction' },
  { id: 'plastic', name: 'Plastic Economy', flow_rate_multiplier: 0.95, description: 'Budget-friendly option' },
  { id: 'ball-bearing', name: 'Ball Bearing', flow_rate_multiplier: 0.85, description: 'Self-closing mechanism' },
  { id: 'cork', name: 'Cork Insert', flow_rate_multiplier: 0.92, description: 'Traditional cork fit' },
  { id: 'rubber', name: 'Rubber Stopper', flow_rate_multiplier: 0.88, description: 'Universal fit' },
  { id: 'long-neck', name: 'Long Neck', flow_rate_multiplier: 1.1, description: 'Extended spout' },
  { id: 'short-neck', name: 'Short Neck', flow_rate_multiplier: 0.95, description: 'Compact design' },
];

export const SEED_RECIPES: Recipe[] = [
  {
    id: 'margarita',
    name: 'Margarita',
    description: 'Classic tequila cocktail with lime and orange liqueur',
    difficulty: 'beginner',
    total_time_target: 12,
    ingredients: [
      { name: 'Tequila', volume_oz: 1.5, sugar_density: 0 },
      { name: 'Lime Juice', volume_oz: 0.75, sugar_density: 0 },
      { name: 'Cointreau', volume_oz: 0.5, sugar_density: 25 },
    ],
  },
  {
    id: 'old-fashioned',
    name: 'Old Fashioned',
    description: 'Timeless bourbon cocktail with bitters and sugar',
    difficulty: 'beginner',
    total_time_target: 8,
    ingredients: [
      { name: 'Bourbon', volume_oz: 2, sugar_density: 0 },
      { name: 'Simple Syrup', volume_oz: 0.25, sugar_density: 50 },
    ],
  },
  {
    id: 'mojito',
    name: 'Mojito',
    description: 'Refreshing rum cocktail with mint and lime',
    difficulty: 'intermediate',
    total_time_target: 14,
    ingredients: [
      { name: 'White Rum', volume_oz: 2, sugar_density: 0 },
      { name: 'Lime Juice', volume_oz: 1, sugar_density: 0 },
      { name: 'Simple Syrup', volume_oz: 0.75, sugar_density: 50 },
    ],
  },
  {
    id: 'negroni',
    name: 'Negroni',
    description: 'Italian classic with gin, Campari, and vermouth',
    difficulty: 'beginner',
    total_time_target: 10,
    ingredients: [
      { name: 'Gin', volume_oz: 1, sugar_density: 0 },
      { name: 'Campari', volume_oz: 1, sugar_density: 24 },
      { name: 'Sweet Vermouth', volume_oz: 1, sugar_density: 15 },
    ],
  },
  {
    id: 'whiskey-sour',
    name: 'Whiskey Sour',
    description: 'Classic sour with bourbon, lemon, and sweetness',
    difficulty: 'intermediate',
    total_time_target: 12,
    ingredients: [
      { name: 'Bourbon', volume_oz: 2, sugar_density: 0 },
      { name: 'Lemon Juice', volume_oz: 0.75, sugar_density: 0 },
      { name: 'Simple Syrup', volume_oz: 0.5, sugar_density: 50 },
    ],
  },
  {
    id: 'daiquiri',
    name: 'Daiquiri',
    description: 'Simple and elegant rum, lime, and sugar',
    difficulty: 'beginner',
    total_time_target: 12,
    ingredients: [
      { name: 'White Rum', volume_oz: 2, sugar_density: 0 },
      { name: 'Lime Juice', volume_oz: 1, sugar_density: 0 },
      { name: 'Simple Syrup', volume_oz: 0.5, sugar_density: 50 },
    ],
  },
  {
    id: 'manhattan',
    name: 'Manhattan',
    description: 'Sophisticated rye and vermouth cocktail',
    difficulty: 'beginner',
    total_time_target: 8,
    ingredients: [
      { name: 'Rye Whiskey', volume_oz: 2, sugar_density: 0 },
      { name: 'Sweet Vermouth', volume_oz: 1, sugar_density: 15 },
    ],
  },
  {
    id: 'moscow-mule',
    name: 'Moscow Mule',
    description: 'Vodka with lime and ginger beer',
    difficulty: 'beginner',
    total_time_target: 10,
    ingredients: [
      { name: 'Vodka', volume_oz: 2, sugar_density: 0 },
      { name: 'Lime Juice', volume_oz: 0.5, sugar_density: 0 },
      { name: 'Ginger Beer', volume_oz: 4, sugar_density: 10 },
    ],
  },
  {
    id: 'cosmopolitan',
    name: 'Cosmopolitan',
    description: 'Stylish vodka cocktail with cranberry and citrus',
    difficulty: 'intermediate',
    total_time_target: 14,
    ingredients: [
      { name: 'Vodka', volume_oz: 1.5, sugar_density: 0 },
      { name: 'Cointreau', volume_oz: 1, sugar_density: 25 },
      { name: 'Lime Juice', volume_oz: 0.5, sugar_density: 0 },
      { name: 'Cranberry Juice', volume_oz: 0.25, sugar_density: 12 },
    ],
  },
  {
    id: 'tom-collins',
    name: 'Tom Collins',
    description: 'Refreshing gin fizz with lemon and soda',
    difficulty: 'intermediate',
    total_time_target: 12,
    ingredients: [
      { name: 'Gin', volume_oz: 2, sugar_density: 0 },
      { name: 'Lemon Juice', volume_oz: 1, sugar_density: 0 },
      { name: 'Simple Syrup', volume_oz: 0.5, sugar_density: 50 },
    ],
  },
];

export const SEED_CHALLENGES: Challenge[] = [
  {
    id: 'single-pour-master',
    name: 'Single Pour Master',
    description: 'Pour exactly 1.5oz in 3 seconds',
    tier: 'beginner',
    target_volume: 1.5,
    time_limit: 3,
    accuracy_threshold: 85,
    unlock_requirement: 0,
  },
  {
    id: 'double-down',
    name: 'Double Down',
    description: 'Pour 2oz in 4 seconds',
    tier: 'beginner',
    target_volume: 2,
    time_limit: 4,
    accuracy_threshold: 85,
    unlock_requirement: 0,
  },
  {
    id: 'quick-shot',
    name: 'Quick Shot',
    description: 'Pour 1oz in 2 seconds',
    tier: 'beginner',
    target_volume: 1,
    time_limit: 2,
    accuracy_threshold: 85,
    unlock_requirement: 0,
  },
  {
    id: 'margarita-speed',
    name: 'Margarita Speed Run',
    description: 'Complete a Margarita in 15 seconds',
    tier: 'beginner',
    target_volume: 2.75,
    time_limit: 15,
    accuracy_threshold: 80,
    unlock_requirement: 0,
    pours_required: 3,
  },
  {
    id: 'precision-test',
    name: 'Precision Test',
    description: '5 consecutive 1oz pours within ±15% accuracy',
    tier: 'beginner',
    target_volume: 1,
    time_limit: 15,
    accuracy_threshold: 85,
    unlock_requirement: 0,
    pours_required: 5,
  },
  {
    id: 'speed-demon',
    name: 'Speed Demon',
    description: 'Pour 1.5oz in under 2 seconds',
    tier: 'intermediate',
    target_volume: 1.5,
    time_limit: 2,
    accuracy_threshold: 90,
    unlock_requirement: 85,
  },
  {
    id: 'half-oz-precision',
    name: 'Half Ounce Precision',
    description: 'Nail a perfect 0.5oz pour',
    tier: 'intermediate',
    target_volume: 0.5,
    time_limit: 2,
    accuracy_threshold: 90,
    unlock_requirement: 85,
  },
  {
    id: 'negroni-rush',
    name: 'Negroni Rush',
    description: 'Equal parts perfection in 12 seconds',
    tier: 'advanced',
    target_volume: 3,
    time_limit: 12,
    accuracy_threshold: 92,
    unlock_requirement: 90,
    pours_required: 3,
  },
  {
    id: 'micro-pour',
    name: 'Micro Pour',
    description: 'Master the 0.25oz pour',
    tier: 'expert',
    target_volume: 0.25,
    time_limit: 1.5,
    accuracy_threshold: 95,
    unlock_requirement: 92,
  },
  {
    id: 'speed-master',
    name: 'Speed Master',
    description: 'Complete 5 perfect pours in 10 seconds',
    tier: 'master',
    target_volume: 1,
    time_limit: 10,
    accuracy_threshold: 95,
    unlock_requirement: 95,
    pours_required: 5,
  },
];